config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trips#index'
  resources :users, only: :show do
    member do
      get 'follow_list'
    end
  end
  
  resources :trips do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :rooms, only: :create do
    resources :messages, only: [:index, :create]
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :prefecture
  has_many   :results, dependent: :destroy
  has_many   :comments, dependent: :destroy
  accepts_nested_attributes_for :results, allow_destroy: true

  validates :title, presence: true
  validates :prefecture_id, numericality: { other_than: 0, message: "can't be blank"}
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.includes(:user).order('created_at DESC')
  end

  def new
    @trip = Trip.new
    @results = @trip.results.build
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.valid?
      @trip.save
      redirect_to trip_path(@trip)
    else
      @trip.valid?
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    go_back(@trip.user, trip_path(@trip))
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @results = @trip.results
    @comment = Comment.new
    @comments = @trip.comments.includes(:user)
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_path
  end

  def search
    @result = Result.new
    if params[:keyword] &&  Result.search(params[:keyword])
      
      @results = Result.search(params[:keyword])
    
      months = [1,2,3,4,5,6,7,8,9,10,11,12]
      monthly_counts = []
      for month in 1..12 do
        c = 0
        @results.each do |result|
          if result.created_at.mon == month
            c += 1
          end
        end
        monthly_counts.append(c)
      end

      @chart = LazyHighCharts::HighChart.new('graph') do |c|
        c.title(text: "月ごとの#{params[:keyword]}の釣果数")
        c.xAxis(categories: months, title: {text: '月'})
        c.yAxis(title: {text: '件'})
        c.series(name: '釣果', data: monthly_counts)
        c.chart(type: 'column')
      end
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :prefecture_id, :content, results_attributes: [:id, :fish_name, :image, :_destroy]).merge(user_id: current_user.id)
  end

  def go_back(owner, path)
    if current_user != owner
      redirect_to path
    end
  end
end

app/views/trips/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message">
          <%= message%>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/trips/_result_fields.html.erb
<div class="nested-fields border p-3 mb-3 border-primary">
  <%= f.label :fish_name, '魚名' %>
  <%= f.text_field :fish_name, class: 'form-control mb-2 result-fish_name-counter' %>
  <%= f.label :image, '画像', class:'result-image-counter' %>
  <%= f.file_field :image %>
  <%= link_to_remove_association 'remove', f, class: 'btn btn-danger' %>
</div>

app/views/trips/edit.html.erb
<div class="container bg-white mb-3 pb-3">
  <h3 class="text-center py-3 my-5">編集</h1>
  <div class="form-wrapper d-grid col-6 mx-auto gap-2 ">
    <%# <form id="form-container" action="" method="post" enctype="multipart/form-data"> %>
    <%= form_with model: @trip, local: true do |s| %>
      <%= render partial: 'error_messages', locals: { model: @trip} %>
      <div class="tripform">
        <%= s.label :title, 'タイトル' %>
        <%= s.text_field :title, placeholder: 'タイトル', class: 'form-control' %>
        <%= s.label :prefecture_id, '都道府県' %>
        <%= s.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-control') %>
        <%= s.label :content, '内容' %>
        <%= s.text_area :content, placehodler: '内容', class: 'form-control' %>
      </div>
      <div class="boundery border-bottom border-top text-center mb-2">釣果</div>
        <%= s.fields_for :results do |t| %>
          <% unless t.object %>
            <%= render 'result_fields', f: t %>
          <% end %>
        <% end %>
        <div class="past-results">
          <%= s.fields_for :results do |t| %>
            <div class="past-result">
              <%= t.object.fish_name %>
              <%= image_tag t.object.image, width: '30%', height: '30%' if t.object.image.attached? %>
              <%= t.label '削除' %>
              <%= t.check_box :_destroy %>
            </div>
          <% end %>
        </div>
        <div class="links">
          <%= link_to_add_association 'add', s, :results, class: 'btn btn-primary' %>
        </div>
      <%= s.submit '送信', class: 'btn btn-block btn-success mt-3 mb-3' %>
    <% end %>

  </div>
</div>

app/views/trips/index.html.erb
<div class="container bg-white mb-3">
<div class="row row-col-2 mt-5">
  <% @trips.each do |trip| %>
    <div class="trip-container col-6 border p-3">
      <div class="trip-title"><%= link_to trip.title, trip_path(trip.id), class: 'text-body h5' %></div>
      <div class="d-flex mt-2">
        <div class="username">投稿日<%= trip.created_at.strftime('%Y/%m/%d %H:%M:%S') %> (<%= trip.prefecture.name %>)</div>
        <div class="username ml-auto">投稿者：<%= link_to trip.user.name, user_path(trip.user), class:'ml-auto, text-body' %></div>
      </div>
      <div class="fish-result my-2">釣果：
        <% trip.results.each do |result| %>
          <%= result.fish_name %>
        <% end %>
      </div>
      <div class="content-container my-2">
        <%= trip.content %>
      </div>
      <div class="image-container">
      <% if trip.results.first %>
        <% if trip.results.first.image.attached?%>
          <%= link_to image_tag(trip.results.first.image, width: '80%', height: 'auto'), trip.results.first.image %>
        <% end %>
      <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/trips/new.html.erb
<div class="container bg-white mb-3 pb-3">
  <h3 class="text-center py-3 my-5">新規投稿</h1>
  <div class="form-wrapper d-grid col-6 mx-auto gap-2 ">
    <%# <form id="form-container" action="" method="post" enctype="multipart/form-data"> %>
    <%= form_with model: @trip, url: trips_path, local: true, method: :post do |s| %>
      <%= render partial: 'error_messages', locals: { model: @trip} %>
      <div class="tripform">
        <%= s.label :title, 'タイトル' %>
        <%= s.text_field :title, placeholder: 'タイトル', class: 'form-control' %>
        <%= s.label :prefecture_id, '都道府県' %>
        <%= s.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-control') %>
        <%= s.label :content, '内容' %>
        <%= s.text_area :content, placehodler: '内容', class: 'form-control' %>
      </div>
      <div class="boundery border-bottom border-top text-center mb-2">釣果</div>
        <%= s.fields_for :results do |t| %>
          <%= render 'result_fields', f: t %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'add', s, :results, class: 'btn btn-primary' %>
        </div>
      <%= s.submit '送信', class: 'btn btn-block btn-success mt-3 mb-3' %>
    <% end %>
  </div>
</div>

app/views/trips/search.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>

<div class="container bg-white mb-3">
  <h3 class="my-5 text-center py-3">検索フォーム</h3>
  <div class="form-wrapper form-group d-flex border-bottom pb-3">
    <%= form_with url: search_trips_path, local: true, method: :get, class: 'form-inline mr-4' do |f| %>
      <%= f.label :fish_name, '魚名: ' %>
      <%= f.text_field :keyword, class: 'form-control' %>
      <%= f.submit '検索', class: 'btn btn-primary' %>
    <% end %>
  </div>
    <% if @chart %>
      <%= high_chart('my_chart', @chart) %>
    <% end %>

  <div class="row row-col-3 mt-5">
  <% if @results != nil %>
  <%= @monthly_counts %>
    <% @results.each do |result| %>
    <div class="trip-container col-4 border p-3">
      <div class="trip-title my-2">
        <%= link_to result.trip.title, trip_path(result.trip.id), class: 'text-body h5' %>
      </div>
      <div class=" mb-2">
        <div class="username">投稿日：<%= result.created_at.strftime('%Y/%m/%d') %>(<%= result.trip.prefecture.name %>)</div>
        <div class="username">投稿者：<a href="{% url 'user_trips' result.trip__user__id %}" class="text-body"><%= result.trip.user.name %></a></div>
      </div>
      <div class="fish-image">
        <%= image_tag result.image, width: '30%', height: '30%', class: 'd-block, mx-auto' if result.image.attached? %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<div class="container bg-white">
  <div class="trip-container col-12 mx-auto gap-2 d-grid py-3 my-5">
    <h2 class="text-center mt-3"><%= @trip.title %></h2>
    <div class="username text-right">投稿日：<%= @trip.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
    <div class="username text-right">投稿者：<%= link_to @trip.user.name, user_path(@trip.user), class:'ml-auto, text-body' %></div>
    <div class="content-container d-flex mr-5">
      <div class="content-name m-2 col-1">
        内容
      </div>
      <div class="content mt-2 ml-3 mr-3 mb-2 col-11">
        <%= simple_format(@trip.content) %>
      </div>
    </div>

    <div class="content-container d-flex">
      <div class="content-name m-2 col-1">
        場所
      </div>
      <div class="content mt-2 ml-3 mb-2 col-11">
        <%= @trip.prefecture.name %>
      </div>
    </div>
    
    <div class="fish-container d-flex">
      <div class="fish-names m-2 col-1">釣果</div>
      <div class="fish-list mt-2 ml-3 mb-2 col-11">
        <div class="fish-name mb-3">
          <% @results.each do |result| %>
            <%= result.fish_name %>
          <% end %>
        </div>
        <div class="fish-image">
          <% @results.each do |result| %>
            <% if result.image.attached? %>
              <%= link_to image_tag(result.image, width: '30%', height: 'auto', class: 'mr-2 img-css'), result.image %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% if user_signed_in? && current_user.id == @trip.user_id%>
      <div class="text-right">
        <%= link_to '編集', edit_trip_path(@trip.id), method: :get, class: 'btn btn-success btn-sm' %>
        <%= link_to '削除', trip_path(@trip.id), method: :delete, class:'btn btn-danger btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

<div class="container bg-white mb-3 pb-3">
    <div class="comment-container container col-8 border-bottom">
      <p class="pt-3">コメント</p>
      <% @comments.each do |comment| %>
        <div class="comment border-top">
          <div class="comment-header d-flex">
            <p><%= link_to comment.user.name, user_path(comment.user), class:'ml-auto, text-body' %></p>
            <p class="ml-auto"><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
          </div>
          <div class="comment-body">
            <%= simple_format(comment.content) %>
          </div>
          <div>
          <% if user_signed_in? && current_user == comment.user %>
            <%= form_with url: trip_comment_path(@trip, comment), method: :delete, class: 'text-right' do |f| %>
              <%= f.submit '削除', class: 'btn btn-danger btn-sm mb-1', id: 'comment_delete_btn' %>
            <% end %>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <div class="form-contaier col-8 mx-auto">
        <%= form_with url: trip_comments_path(@trip.id), model: @comment, method: :post, local: true, class: 'p-3' do |f| %>
          <%= f.label :content, '内容', class: 'col-8 mx-auto' %>
          <%= f.text_area :content, class: 'form-control  mx-auto' %>
          <%= f.submit '送信', class: 'btn btn-primary btn-block  mt-3 mx-auto' %>
        <% end %>
      </div>
    <% end %>
</div>