config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trips#index'
  resources :users, only: :show do
    member do
      get 'follow_list'
    end
  end
  
  resources :trips do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :rooms, only: :create do
    resources :messages, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :trips, dependent: :destroy
  has_many :comments, dependent: :destroy
  # depentent: :destroy検討
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages

  validates :name, presence: true

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    follow_ids = []
    self.relationships.each do |r|
      follow_ids.append(r.follow_id)
    end
    follow_ids.include?(other_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @trips = @user.trips
  end

  def follow_list
    @room = Room.new
    @user = User.find(params[:id])
    @relationship = Relationship.new
    if user_signed_in?
      user_ids = [current_user, @user]
      @room_exist = Room.room_exists?(user_ids)
    end
  end
end

app/views/users/follow_list.html.erb
<div class="container bg-white mt-5 ">
    <div class="col-6 mx-auto pt-5 pb-5 text-center">
      <h3><%= link_to @user.name, user_path(@user), class: 'text-body' %>のフォローリスト</h3>
        <% if user_signed_in? %>
          <% if not current_user.id == @user.id and not current_user.following?(@user) %>
            <%# <form action="{% url 'follow' pk %}" method="post"> %>
            <%= form_with url: relationships_path(@user), model: @relationship, method: :post, local: true do |f| %>
              <%# <input class="btn btn-sm btn-primary" type="submit" value='フォローする' > %>
              <%= f.hidden_field :follow_id, value: @user.id %>
              <%= f.submit 'フォローする', class: 'btn btn-sm btn-primary', id: 'follow_create_btn' %>
            <% end %>
            <%# </form> %>
          <% elsif current_user.id != @user.id %>
            <%# <form action="{% url 'unfollow' pk %}" method="post">
              <input class='btn btn-sm btn-danger' type="submit" value='フォローを外す' >
            </form> %>
            <%= form_with url: relationship_path(@user), model: @relationship, method: :delete, local: true do |f| %>
              <%= f.hidden_field :follow_id, value: @user.id %>
              <%= f.submit 'フォローを外す', class: 'btn btn-sm btn-danger', id: 'follow_delete_btn' %>
            <% end %>
          <% end %>
        <% end %>

        <div class="message-button mt-3">
          <% if user_signed_in? and current_user.id != @user.id %>
          <%# {% if user.is_authenticated %}
          {% if user.id != object.id %}
            {% if mutural_follow or room_exist %} %>
            <% if (current_user.following?(@user) and @user.following?(current_user)) or @room_exist %>
              <%# <form action="{% url 'room_create' pk %}" method="post">
                <input class='btn btn-sm btn-info' type="submit" value="メッセージ">
              </form> %>
              <%= form_with url: rooms_path, model: @room, local: true, method: :post do |f| %>
                <%= f.hidden_field :user_ids, name: "room[user_ids][]", value: @user.id %>
                <%= f.hidden_field :user_ids, name: "room[user_ids][]", value: current_user.id %>
                <%= f.submit 'メッセージ', class: 'btn btn-sm btn-info', id: 'message_btn' %>
              <% end %>
            <% end %>
          <%# {% endif %}
          {% endif %} %>
          <% end %>
        </div>
    </div>

    <div class="d-flex">
      <div class='col-6'>
        <h5>以下のユーザーをフォローしています(<%= @user.followings.count %>)</h5> 
        <% @user.followings.each do |following_target| %>
          <div class="follower border p-2 m-1">
            <div>
            <%= link_to following_target.name, follow_list_user_path(following_target), class: 'text-body' %>
            (投稿数 :  <%= following_target.trips.count %>)
            <%= link_to '投稿履歴', user_path(following_target), class: 'text-secondary' %>
            <%= link_to 'フォローリスト ', follow_list_user_path(following_target), class: 'text-secondary' %>
            </div>
            <div>
              <%= simple_format(following_target.introduce) %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-6">
      <h5>以下のユーザーによってフォローされています(<%= @user.followers.count %>)</h5>
      <% @user.followers.each do |follower| %>
        <div class="followed border p-2 m-1">
          <div>
            <%= link_to follower.name, follow_list_user_path(follower), class: 'text-body' %>
            (投稿数 :  <%= follower.trips.count %>)
            <%= link_to '投稿履歴', user_path(follower), class: 'text-secondary' %>
            <%= link_to 'フォローリスト ', follow_list_user_path(follower), class: 'text-secondary' %>
          </div>
          <div>
            <%= simple_format(follower.introduce) %> 
          </div>
        </div>
      <% end %>
      </div>
    </div> 
  </div>
</div>

app/views/users/show.html.erb
<div class="container bg-white mb-3">
  <h3 class="text-center mt-5 pt-3"><%= @user.name %>の投稿履歴</h1>
  <div class="wrapper d-flex">
    <div class="user-info col-4 mt-5 mr-3">
    <p>ユーザー名：<%= @user.name %></p>
    <p>投稿数：<%= @trips.count %></p>
    <p><%= link_to '>>フォローリスト', follow_list_user_path(@user), class: 'text-primary' %></P>
    <p>自己紹介</p>
    <div class="intro-content mb-3 border-top border-bottom py-2">
      <%= simple_format(@user.introduce) %>
    </div>
    <% if user_signed_in? && @user.id == current_user.id %>
      <%= link_to '編集', edit_user_registration_path(@user.id),  class: 'btn btn-success btn-sm'%>
    <% end %>
  </div>
  
  <div class="index col-8">
    <div class="row row-col-2 mt-5">
      <% @trips.each do |trip| %>
        <div class="trip-container col-6 border p-3">
          <div class="trip-title"><%= link_to trip.title, trip_path(trip.id), class: 'text-body h5' %></div>
          <div class="d-flex">
            <div class="username">投稿日<%= trip.created_at.strftime('%Y/%m/%d') %>(<%= trip.prefecture.name %>)</div>
            <div class="username ml-auto">投稿者：<%= @user.name %></div>
          </div>
          <div class="fish-result my-2">釣果：
            <% trip.results.each do |result| %>
              <%= result.fish_name %>
            <% end %>
          </div>
          <div class="content-container my-2">
            <%= trip.content.truncate(5) %>
          </div>
          <div class="image-container">
          <% if trip.results.first && trip.results.first.image.attached? %>
            <%= link_to (image_tag trip.results.first.image, width: '80%', height: 'auto'), trip.results.first.image %>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <%# <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28 mt-5">
          <!-- 前へ の部分 -->
          {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                      <span aria-hidden="true">&laquo;</span>
                  </a>
              </li>
          {% endif %}

          <!-- 数字の部分 -->
          {% for num in page_obj.paginator.page_range %}
              {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                  {% if page_obj.number == num %}
                      <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                  {% else %}
                      <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
              {% endif %}
          {% endfor %}

          <!-- 次へ の部分 -->
          {% if page_obj.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                      <span aria-hidden="true">&raquo;</span>
                  </a>
              </li>
          {% endif %}
      </ul>

    </nav> %>
  </div>
</div>
</div>